epochs: [100]
min_lr: [0]
virtual_node: [0]
lr_schedule_patience: [101]
tracking: [0]
JK: ["concat"]

cat: [1]
lr_scheduler: ["None"]

model: ["GIN"]
batch_size: [32]
emb_dim: [300]
drop_out: [0.5]
num_layer: [5]
pooling: ["mean"]
lr:  [0.001]
num_mlp_layers: [2]
